FROM node:22 AS dev

WORKDIR /app

RUN groupadd -r appgroup && useradd -r -g appgroup appuser


COPY package*.json ./

RUN npm ci

COPY . .

RUN npx prisma generate

RUN chown -R appuser:appgroup /app

USER appuser

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
